* 01 (Âb-ı Hayat) (Diyanet Vakfı İslam Ansiklopedisi) - Your Highlight on page 1446 | Location 22164-22168 | Added on Monday, April 24, 2017 2:16:30 AM

Daha sonra Adriyatik denizi sahillerindeki Bari liman şehri ele geçirildi. Aynı yıllarda Venedik önlerine gelen müslümanlar 846 yılında Ostia’ya çıkarma yaparak Batılılar’ın Eternal City (ebedî şehir) dedikleri Roma’yı tehdit ettiler, ancak Roma’nın müstahkem surlarını aşamayıp Saint Peter Katedrali ile Saint Paul Katedrali’ni yağma ettiler. II. İbrâhim de 902 yılında vefatından önce Messina boğazını aşarak İtalya’nın güneyindeki Calabria toprakları üzerinde cihad harekâtında bulundu.
* 01 (Âb-ı Hayat) (Diyanet Vakfı İslam Ansiklopedisi) - Your Highlight on page 1452 | Location 22262-22265 | Added on Monday, April 24, 2017 3:11:04 AM

Cumhuriyet’in ilk yıllarında ağnam resmi, “hayvan sayım vergisi” olarak varlığını ismen sürdürdü. 1924 bütçesinde âşâr, arazi vergisi ile birlikte ağnam vergisi devlet gelirlerinin %35’ini oluşturuyordu. Ancak verginin payı giderek azalmaya başladı. Bütçe gelirlerindeki payı 1938’de %19 iken, 1959’da %0.5’e düştü. Nihayet 1962’de tamamen kaldırıldı.
* 01 (Âb-ı Hayat) (Diyanet Vakfı İslam Ansiklopedisi) - Your Highlight on page 1459 | Location 22365-22372 | Added on Monday, April 24, 2017 3:19:16 AM

Şu halde Ahd-i Atîk’teki “Ararat dağları” ifadesini, bugünkü Ağrı dağı yerine, Van gölünün güneyindeki dağlar olarak anlamak daha doğrudur. Nitekim tûfanla ilgili eski Babilonya hikâyesinde geminin Nisir dağının tepesine oturduğu nakledilmektedir ki bu dağ, daha güneyde Asur topraklarının doğusunda (bk. C. F. K., JE, II, 74) muhtemelen Aşağı Zap suyuyla Dicle’nin doğusu arasındaki bölgede yer almaktadır (bk. J. Skinner, DB, s. 49). Kaldeli rahip Berosos’un tarihinde geminin Urmiye (Urumiah) yönünde Musul’un kuzeydoğusundaki Kurt dağı üzerine oturduğu yazılıdır (bk. C. F. K., JE, II, 74). Tekvîn 8/4’ün Ârâmîce ve Süryânîce tercümeleri geminin indiği dağı Ture Kardu olarak zikreder ki burası Van gölünün güneydoğusundaki dağlardır (bk. Tikva S. Frymer, Ejd, III, 290). Süryânî yorumculara göre Ture Kardu, Kur’an’da da geminin indiği dağ olarak gösterilen (bk. Hûd 11/44) Cûdî dağıdır (Aziz Günel, s. 29).
* 01 (Âb-ı Hayat) (Diyanet Vakfı İslam Ansiklopedisi) - Your Highlight on page 1461 | Location 22390-22395 | Added on Monday, April 24, 2017 3:21:25 AM

1937’de Binbaşı Cevdet Sunay, on beş subay ve elli erle birlikte Ağrı dağının zirvesine ulaşmıştır. Bu heyet, iddiaların aksine, Nûh’un gemisinin enkazına rastlamamıştır. 23 Temmuz 1968’de Albay Turhan Selçuk başkanlığında on sekiz subay, on altı astsubay ve yüz on iki erden oluşan heyet zirveye çıkmıştır. Yakın geçmişte ise Amerikalı astronot Irwin birkaç defa dağa tırmanarak gemiden kalma parçalar bulduğunu iddia etmiştir. Ancak bütün bu iddialara karşı Nûh’un gemisinin kalıntılarının Ağrı dağında bulunduğuna dair şimdiye kadar hiçbir müsbet delil ortaya konamamış olması dikkat çekicidir.
* 01 (Âb-ı Hayat) (Diyanet Vakfı İslam Ansiklopedisi) - Your Highlight on page 1462 | Location 22413-22414 | Added on Thursday, April 27, 2017 7:28:30 AM

Allah, kendine dost olarak seçtiği velîleri ağyârın gözünden saklamıştır. Nitekim kudsî bir hadiste, “Velîlerim kubbelerimin altındadır, onları benden gayrısı bilemez” buyurulmuştur.
* 01 (Âb-ı Hayat) (Diyanet Vakfı İslam Ansiklopedisi) - Your Highlight on page 1462 | Location 22416-22420 | Added on Thursday, April 27, 2017 7:29:18 AM

Tasavvuf ve tarikat sırrîlik esasına dayandığı için, sûfîlerin ve tarikat ehlinin arasına yabancıların girmesi genellikle pek hoş karşılanmaz. Çünkü yabancıların (ağyâr) bulunduğu meclislerde safâ ve mânevî zevk hali tam gerçekleşmez, bast* ve keşf* hali ortaya çıkmaz. Cüneyd-i Bağdâdî’ye göre sûfîler bir ailenin fertleri gibidir, aralarına ağyâr giremez. O, tasavvuf ilmini öğrettiği yerlere yabancıları almazdı.
* 01 (Âb-ı Hayat) (Diyanet Vakfı İslam Ansiklopedisi) - Your Highlight on page 1468 | Location 22500-22507 | Added on Thursday, April 27, 2017 8:12:14 AM

Bütün bunlardan sonra denebilir ki ahadiyyet gerçek, aşkın (müteâl), eşsiz ve yüce birliği ifade etmektedir. Bu şekilde mutlak bir tenzihe ulaşabilmek için Allah’ı müsbet sıfatlardan çok menfi (selbî) sıfatlarla nitelemek gerekir. Çünkü müsbet sıfatlar, bir anlamda tarif ve tahdit ifade eder; ayrıca onlar bizim Allah hakkındaki sübjektif tasavvurlarımızdır. Selbî sıfatlarda ise böyle bir şey söz konusu değildir; bu bakımdan mutlak bir tenzihe ulaşmak selbî sıfatlarla mümkün olmaktadır. O halde bu “bir”, bizce niteliği bilinmeyen (mechûlü’n-na‘t) ve kendisine hiçbir şekilde işaret edilemeyen (münkatiu’l-işârât) birdir. Bilinemez olduğu için ona sırrü’s-sır, gaybü’l-gayb, gayb-ı mutlak, gayb-ı hüviyyet, amâ-i mutlak da denilmiştir. Bu tam anlamıyla bir bilinemezlik (agnostizm)dir. Çünkü ahadiyyetin üzeri ululuk (celâl) ve yücelik (teâlî) perdesiyle öyle sıkı bir şekilde örtülmüştür ki onu bilmek ve tanımak imkânsızdır.
* 01 (Âb-ı Hayat) (Diyanet Vakfı İslam Ansiklopedisi) - Your Highlight on page 1469 | Location 22516-22518 | Added on Thursday, April 27, 2017 8:13:24 AM

Abdülkerîm el-Cîlî’ye göre, “Bir insan sırf kendi benliğini dikkate alarak düşünür ve tefekkürünü bunun dışında hiçbir şeye çevirmezse, bu onun ahadiyyeti olur”.
* 01 (Âb-ı Hayat) (Diyanet Vakfı İslam Ansiklopedisi) - Your Highlight on page 1471 | Location 22542-22546 | Added on Thursday, April 27, 2017 8:15:33 AM

Âharlanmış kâğıt üzerinde teşekkül eden koruyucu tabaka, kâğıdın sathını düzgün ve kolay yazılabilir hale getirdiği gibi, mürekkebin emilmesine de engel olarak gerektiğinde kâğıda zarar vermeden düzeltme yapılmasına ve yazının kolayca silinerek yeniden yazılmasına imkân verir. Bazan nemli pamuk veya süngerle silerek, çok defa da hafifçe kazımak ve ekseriya yalamak suretiyle gereken düzeltmeler yapılabilir. Türkçe’de okumuş yazmış kişiler için eskiden kullanılan “mürekkep yalamış” tabiri de buradan doğmuştur.
* 01 (Âb-ı Hayat) (Diyanet Vakfı İslam Ansiklopedisi) - Your Highlight on page 1474 | Location 22600-22603 | Added on Tuesday, May 2, 2017 12:10:37 AM

Hz. Peygamber’in, “Yahudi ahbârından on tanesi bana iman etseydi yeryüzündeki bütün yahudiler de müslüman olurdu” meâlindeki hadisi (bk. Müsned, II, 346), ahbârın yahudiler arasındaki nüfuzunu göstermektedir. Yine muhtelif hadisler, Asr-ı saâdet’teki ahbârın Hz. Peygamber’le olan münasebetlerini, çeşitli sorular sormak suretiyle onu imtihan edişlerini, Tevrat hükümlerini gizlemeye veya tahrif etmeye kalkışmalarını haber vermektedir
* Brandwashed: Tricks Companies Use to Manipulate Our Minds and Persuade Us to Buy (Martin Lindstrom;Morgan Spurlock) - Your Highlight on page 7 | Location 106-108 | Added on Saturday, December 23, 2017 1:34:37 AM
