#+TITLE: Zerkubia Seyahati
#+AUTHOR: Emin Reşah
#+DATE: Sun Sep 27 22:12:59 EEST 2015 -- 13223

* Yazı notları
** <2015-12-28 Mon>

Sjacin'in kafaısndan geçenlerin hepsini birden Zaib'e aktarmaya çalışmanın
manasız olduğuna karar verdi. Buu nasıl yapabilirim? İnsanın değişmmesini kabul
etmek neden bu kadar zor.

Beni artık tanımıyorsun diyecek gibi oldu. Beni artık buraya gelmeden önceki
kafamla anlayamazsın. Zaib ona garip garip baktı. Buraya geldikten sonra
ddeğiştiğini biliyorum ama bu kadar önemli bir değişiklik beklemiyordum. Unuttun
mu, burada insanların hep seni küçük gördüklerini söylemiştin.

Hayır, bu

Evet. Burada insanların beni küçük gördüklerini düşünüyordum ama sanırım
başkaları da bunu benim için düşünüyor. Bunlar sakin insanlr, içe dönük bir
toplum burası, onun için kibirli saılıyor. ;nsanların bunu anlaması zor, çünkü
içe dönüklük veya sıkılganlık başkalarınca, aslında olmadığı şekilde kibir
olarak adalndırlıyor.


* Zerkubia Seyahati

İki kişinin biri Aerkek, diğeri Bkadın. Bunların şimdilik kullanalım,
daha sonra içlerini doldururuz.

Toplamda 100.000 kelime hedefliyorum.

* Dramatis Personae

** Zaib

Liberal, beyaz yakalı bir çalışan, yönetici olarak çalışıyor bir yerde. Arap
görünüşlü, kıvırcık saçlı.

Elektronik kağıt işi yapıyor: [[file:3.rst::standart%20ka%C4%9F%C4%B1t%20m%C4%B1,%20elektronik%20ka%C4%9F%C4%B1t%20m%C4%B1%20oldu%C4%9Funu%20anlamak%20i%C3%A7in%20elini][İlk gördükleri]]

Elektronik kağıt, Kindle ekranına benzeyen ama çok ince, renklendirilebilen bir
elektronik malzeme.

** Sjacin

Sosyalist ve gazeteci. Sol liberal denebilir ama eskisinde silahlı mücadele
peşinde de koşmuş. Siyasetle ilgilenmekten liseyi zor bitirmiş.

Bu ikisi sevgili. Evlenmeyi düşündükleri oluyor ancak evlilik kavramından ikisi
de farklı şeyler anlıyor.

Zerkubia'da bulunmasının sebebi çevre örgütlerinin temsilcileriyle röportajlar
yapmak ve onların Konvansiyon'un uygulamaya koyduğu çeşitli önlemler konusunda
ne düşündüklerini anlamak. Dışarıdan gazeteci gibi duruyor, ancak aslen orta
boyutta bir istihbarat elemanı. Konvansiyon'un üretimi azaltma fikrine, buradaki
çevre örgütlerinin nasıl yaklaşacağını sorguluyor. Asıl dertleri Zerkubia'yı
Konvansiyon'a katmak olan bir çalışmanın parçası. Ancak kendisi de bu çalışmanın
parçası olduğundan emin değl. 

** Kevni

Zaib'in arkadaşı. Zaib üniversitedeyken İstatistik dersinde
asistanmış. İstatistik doçenti gibi bir işi var. Sjacin'in ülkeye
geleceğini duyunca onları davet eden ilk arkadaşları. 

** Zerkubia'ya ne için gidiyorlar?

Sjacin'in Zerkubia'da bulunmasının sebebi çevre örgütlerinin temsilcileriyle
röportajlar yapmak ve onların Konvansiyon'un uygulamaya koyduğu çeşitli önlemler
konusunda ne düşündüklerini anlamak. Dışarıdan gazeteci gibi duruyor, ancak
aslen orta boyutta bir istihbarat elemanı. Konvansiyon'un üretimi azaltma
fikrine, buradaki çevre örgütlerinin nasıl yaklaşacağını sorguluyor. Asıl
dertleri Zerkubia'yı Konvansiyon'a katmak olan bir çalışmanın parçası. Ancak
kendisi de bu çalışmanın parçası olduğundan emin değl.

Bunun yanında bir de insan hakları raporu çalışması var. Zerkubia'nın insan
hakları konusunda Konvansiyon istismar edecek bir şeyler arıyor. Sjacin'in
dertlerinden biri bunu bulmak. 

Zaib onunla beraber tatil yapıyor. Ancak bir yandan da iş görüşmesi yapmak
istiyor. Birkaç arkadaşını da ziyaret edecek. 

* Jemmieler. 

Zaib: Duvadeel 
Sjacin: Hemriaton. 

Duvadeel: Hayatının merkezine başarıyı ve çalışmayı koyan, kulüp ve
okulları olan, ikiyüzonbin kişilik bir topluluk.*

Hemriaton: Sosyalist görüşlerin öne çıktığı, entelektüel tartışma ve
dergileriyle öne çıkan seksenikibin kişilik bir topluluk. Gazeteci,
yazar, entel, dantel tipli insanları çeker.

* [[file:3.rst::s%C3%BCtunlar%C4%B1ndan%20buran%C4%B1n%20devlete%20ait%20oldu%C4%9Fu%20anla%C5%9F%C4%B1l%C4%B1yordu.%20*%C4%B0lk%20Milyonlar][Milyonlar Meclisi]]
* Zerkubca Alfabesi ve İmlası

Zerkubca'yı Türkçe gibi yazacağım, ancak farklı bir dil olduğunu
göstermek için farklı bir alfabe kullanmaya karar verdim. Türkçe için
oluşturmaya çalıştığım, etimolojik alfabeyi burada kullanacağım. 

a, e, ı, i, o, ö, u, ü sadece kelime köklerinde kullanılıyor. 

ee, ei, eu: elif. ikinci ses geçerli ancak arapça köklerde kullanılıyor. 

aa, aı, ai, au: ayn. ikinci ses gibi okunuyor ancak arapça köklerde geçerli. 

ea: uzun a, elif med

ii: uzun i, ye med. 

uu: uzun u, waw med. 

b, c, ç, f, 

ch: ç

d: d ve dal
dz: dad. bazen z, bazen d okunuyor. ramadzean 

gy: yumuşak ğ ve ğayn.

q: kaf
k: kef
kn: nazal n

h: he
x: xa
xx: xı

z: ze
zj: zel
zh: zı

s: sin
sj: se, s okunuyor
sz: sad, s okunuyor
sh: ş

t: te
td: tı 

l: lam
m: mim
n: nun
w: waw, arapça ve farsça kelimelerde
we, wu, wü, wı, wi: hareke almış waw
v: türkçe kelimelerde v

y: y

tdagy tdagya qavushmz einsean einsana qavushr

aibeadeullah emre sheahiin

emin reshah

bismeillah 

xxoweaca

leaf wü gwüzeaf 
* İsimler: 

- [[file:3.rst::Jemmiyeler%20park%C4%B1,%20Zerkuwb%20%C5%9Fehrinin%20ortas%C4%B1nda,%20eski%20g%C3%BCnlerin%20ve][Zerkuwb]] Başşehrin adı. 
- [[file:4.rst::ya%C5%9Fam%C4%B1%C5%9F,%20Eliyas%20Efra%20ad%C4%B1.%20*Oniki%20Senet*%20diye%20bir%20kitab%C4%B1%20var,%20o%20zaman%C4%B1n][Eliyas Efra]]

* Zerkubia Tarihi Notları

.. :Author: Emin Reşah
.. :Date:   12894

Hakiki Devrim'e Kadar
---------------------

Zerkubia'da tarihin ilk izlerine 6000 yıl kadar önce rastlıyoruz. Bu
hemen hemen diğer uygarlıkların tarıma başladığı bir
zaman. Zerkubia'nın tarihini komşularının tarihini anlatarak
başlayalım.

Zerkubia doğuda Sernedeb dağları ve batıda Guyral çölüyle çevrilmiş
bölgeye verilen bir ad. Bu bölgede M.Ö. dördüncü bin yıldan itibaren
şehirlerin kurulduğunu bıraktıkları izlerden biliyoruz. Antik Çağ'da
Sümerlilerin Zerkublarla ilişki kurdukları ve ticaret yaptıkları
anlaşılıyor. Sümer'e bakır sattıkları ve karşılığında tahıl
aldıklarını gösteren çeşitli çivi yazısı tabletler bulundu. Çinlilerin
atalarıyla da ilişki kurdukları, Çin arşivlerinde yer alan
Tse-Ku-Ba'nın onlar oldukları iddia ediliyor.

Zerkubia'nın tarihinde üç önemli savaş ve bu üç önemli savaşın yol
açtığı üç önemli kıyım vardır. Zerkubia tarihi bu savaşlardan
hareketle anlatılır. Bunlardan birincisi Miladî ikinci yüzyıldaki
Metanon savaşıdır. Metanon savaşında Zerkubia ikiye bölünmüş ve ondan
sonraki altıyüz yıl iki ayrı kral tarafından yönetilmiştir. İkinci
savaş 916 yılında, Doğu Zerkubia krallığının çöküşüyle sonuçlanan
Hutti savaşıdır. Üçüncüsü ise krallığın sonunu ve *Hakiki Devrim*
dedikleri olayların başlangıcını getiren Zerkubb şehri kuşatmasıdır.

Metanon savaşı, Kral Hetermes'in oğulları arasında çıkan taht
kavgasının zirve noktasıydı. Metanon'da Hetermes'in büyük oğlu Zemb ve
ortanca oğlu Dukkadim çarpıştı. Bu savaşın sonunda Zerkubia'da
savaşacak erkek kalmadığı anlatılır. İki taraf da kendilerine ait
şehirlere çekildi, Zemb Doğu Zerkubia'nın, Dukkadim ve kardeşi Ts'ev
Batı Zerkubia'nın yönetimini üstlendiler.

Zerkubia tarihinde *Büyük Bölünme* diye geçen bu olayın izlerini
sonraki altıyüzyılda görebiliriz. Doğu Zerkubia krallığı denize de
uzak olmanın getirdiği sıkıntılardan dolayı eski ihtişamına asla
kavuşamadı. Batı Zerkubia da birkaç defa geçirdiği veba salgınlarından
dolayı tekrar Doğu'nun üstüne yürüyecek kadar
toparlanamadı. Bölünmüşlüğün bu kadar uzun sürmesinde bunların etkili
olduğu söylenmektedir.

Dukkadim hanedanı Doğu'ya tekrar yürümeye karar verdiğinde, Metanon
savaşı bir efsane haline gelmişti. İki tarafın da artık birbirini
anlamayacak kadar farklı diller konuştuğunu yazılardan
biliyoruz. Zerkubb'ların meşhur kindarlığına dair verilen örneklerin
başında altıyüzyıl sonra bir savaşın hesabını görmeye çalışmak vardır.

Hutti savaşı Metanon gibi başlamadı. Kimin kazanacağı belli sayılırdı.
Ancak Doğu Zerkubia, Batı'daki bazı derebeylerine bağımsızlık sözü
verince ordular bölündü ve Batı ordusu birbirine düştü. Batı Zerkubia
Kralı Perevnes'in önce bu derebeylerini yenmesi, daha sonra Doğu
Zerkubia'ya yürümesi gerekti. Savaş oniki yıl sürdü.

Bu oniki yılda Doğu Zerkubia'daki sekiz şehrin tamamen yakıldığı
anlatılır. Doğu Zerkubia başşehri Hudan-Vut'taki tüm önemli binaların
tek tek söküldüğü ve taşlarının diğer şehirlere taşındığı kaydederler.
Hudan-Vut'un daha sonra Sezaman nehrine bent yapılarak su altında
bırakıldığı tahmin edilmekte. Bugünkü Douh gölünün bulunduğu yerde
olduğu söyleniyor.

Bu iki savaşla beraber anılan *Doğru Devrim* veya *Hakiki Devrim* ise,
yirmiiki yıl sürdü.

Devrim
======

Zerkubia aristokrasisi Zerkubia'da birleşik krallığının hüküm sürdüğü
yaklaşık bin yıl boyunca, sosyal manada yerlerinde kalmış ailelerden
oluşuyordu. Zerkublar Dışarıdan ciddi tehdit görmeyen ancak devamlı
bir yabancı korkusuyla bir arada tutulan bir toplumdu. Bu toplumda
aristokrasinin gayesi de, bulundukları konumu riske atmadan yaşamaya
devam etmekti.

Cumhuriyet devrimi, diğer ülkelerde bu çeşit bir aristokrasiyi yok
ettiği halde, Zerkubia'da aristokrasinin büyük kısmı sermaye sahibi
olabilecek tek sınıf olduğundan, burjuvaya dönüştü. Asırlardır iki
sınıflı yaşayan toplumda, onlardan başka dışarıyla iletişim kurup,
ticari ilişki geliştirebilecek kimse de yoktu. Cumhuriyet gerçekte
sadece Kral ailesinin öldürülmesiyle sonuçlanmış bir devrimdi ve o
zamandan *hakiki devrim* dedikleri devrime kadar, Cumhuriyetin
idarecileri hep bu aristokratik burjuvazinin belirlediği kimseler
olmuştu. Zerkubia tarihin oligarşik cumhuriyet dönemi. 

Alt sınıflar Cumhuriyet öncesi devirde *serf*, Cumhuriyetten sonra
*işçi* konumundaki büyük halk yığınlarıydı. Monarşi günlerinde de bu
insanların bazı hakları vardı ve tam bir kölelik yoktu. Serflerin
rızası dışında alınıp satılması mümkün değildi ancak *efendi
değiştirmek* için, transfer ücreti cinsinden ufak meblağlar onlara
yetiyordu. Cumhuriyet sonrasındaysa, bu hukuk büyük ölçüde devam etti.
Toprağa bağlı ırgatların yerini, fabrikaya bağlı işçiler aldı.

Öteden beri bu insanların sadece hayatlarını idame ettirecek kadar
para kazanmaları bir devlet politikası olmuştu. Birikim yapacak,
toprak alacak, kendilerine mülk alacak kadar bir gelirleri olması,
hayli istisnai durumlar dışında imkansızdı. Cumhuriyet'ten sonra bile
Zerkubia tarihin gördüğü en stabil kölelik toplumlarından biriydi.

Hakiki Devrim
=============

Hakiki devrimin gelişmesinde üç etkenin rol oynadığı
söylenmektedir. Birincisi aristokratik burjuvazinin umursamazlığı,
ikincisi onlarla işbirliği yapan politikacıların yolsuzlukları ve
üçüncüsü sistemin insanlara değişim için umut vermeyişi.

Devrim yirmi iki yıl sürüyor. Bu yirmi iki yıl içinde bazıları farklı
şehirlerde olmak üzere, en sağdan en sola bir çok politik sistem
denemesi yapıyorlar. Adeta bir siyasi sistem müzesi oluyor
ülke. Devrim başladığında en kuvvetli muhalifler sosyalistler ancak
birkaç yıl içinde onların da hayal dünyasında yaşadıkları anlaşılıyor.

Sosyalistleri devirenler, başta onlarla beraber hareket etmiş
anarşistler oluyor. Ancak devirdikten sonra kendi aralarında
anlaşamadıkları için ülke toptan bir iç savaşa sürükleniyor. Bu
içsavaş, yerel liderlerin kendi feodalizmlerini kurmasıyla
sonuçlanıyor.  Ülke tarihinde hiç olmadığı kadar parçalanıyor.

Bu derebeylerinden biri, şimdilerde *Menkuşe* adıyla anılan bir bey,
ortaya çıkıp, kuzeybatıdaki kendi ülkesinde *Çeghrudz* adını verdiği
bir vakıf/topluluk kuruyor. Menkuşe devrimlerin başlangıcından onsekiz
yaşında olduğunu söylediğine göre, bu vakfı kurduğunda yirmisekiz
yaşında olmalı. Babasının Çeghrudz valisi olduğu biliniyor, ancak
devrimin başlangıcında görevden alınıp hapse atılıyor. *Çeghrudz
günleri* isimli kitapçesinde o günleri şöyle anlatıyor: 

.. note:: LEFT HERE

 Babamın hapse atılmasından sonra Devrim bi 

*Çeghrudz* savaş döneminde, tutunacak dalı kalmamış bir grup insanın
bir araya gelip, yardımlaşması amacıyla kuruluyor. Yardımlaşma
kurumları savaştan önce de önemil kurumlar ancak pek çok eski kurumda
olduğu gibi itibar kaybına uğramış, insanların *hilekarlık* olarak
görmesine sebep bir çok olayın neticesi asli fonksiyonlarından şüphe
edilmeye başlanmış.  *Menkuşe* bu itibar kaybına uğrayan kurumların
yaptıkları yanlışları düşünmüş ve *devlet* denen müessese de dahil,
etrafındaki tüm kurumların yardımlaşma kurumlarının bozulmuş halleri
olduğuna kanaat etmiş.

*Çeghrudz* *Menkuşe*'un fikirlerinin bir denemesi olarak ortaya çıkmış.
Halihazırda Zerkubia anayasasının da temelini oluşturan fikirleri
dünyanın geri kalanındakilere benzemeyen fikirler içeriyormuş.

------

Devrimden önce Menkuşe çalışmadığı zamanları yazarak geçirmiş. Bunlardan
iki kitap ortaya çıkmış. Derler ki, bu kitaplardan *Teori* adı
verilenini kimse anlamaz ve *Pratik* adı verileni herkes
anlar. Kitaplara adlarını talebeleri vermiş, kendisinin bu tasnifi ne
şekilde yaptığı bilinmiyor.  Ancak söylenen, ortalamaya hitap edenleri
*Pratik* adında topladığı ve bunun dışındakileri de *Teori* diye
isimlendirdiği.

*Teori* yedi bölümden oluşuyor ve Anlambilimle başlayıp, Sosyal
Teoriyle bitiyor. Psikoloji, Felsefe ve Ekonomi konusunda fikirlerini
içeren bölümleri var. Kitabın tamamını okumadım, okullarda işleniyor
ancak ders kitabı olarak kullanılan hali kısaltılmış ve içine bol bol
açıklama konmuş.

*Teori* çok uzun değil, takriben 200 sayfa kadar. Batı felsefesinden
alıştığımız teorik metinlerden çok Konfüçyüs'ün sözlerine benzeyen bir
tarafı var. *Menkuşe* hemen hiçbir metafizik tartışmaya
girmemiş. Eliptikliğin sebebi işlediği konuların zorluğu değil, kendi
tabiriyle *kelimeleri yıkamak*.

Zerkubia'da *Menkuşe* hakkında araştırma yapan bir profesörle tanışmıştım.
Ona bu tabiri sorduğumda, *kelimeleri çamurdan ve anlamsızlıktan
yıkamak* demişti. İçimden *evet, çok anlaşılır oldu* dediğimi
hatırlıyorum. Sonradan diline vakıf oldukça, Menkuşe'un bu sözdeki
maksadının mümkün mertebe kendi içinde tutarlı ve metinbağını
(bağlamı) kendi içinde taşıyan sözler olduğunu düşünüyorum. *Metinbağı
çamurdur* diye bir sloganı var mesela, anlamdan bahsederken. *Çamurdan
yıkamak* dedikleri de, sözün söylenme sebebinden bağımsız bir anlamı
olup olmadığına bakmak. 

Metinbağı olmadan anlamın mümkün olup olmadığına dair tartışmalar hala
devam ediyor. Bazı talebeleri, onun bu duruşuyla aslında insanlara
sözlerin *anlamsızlığını* göstermeyi hedeflediğini, *çamurdan
yıkadığımızda* sözde hiçbir şey kalmayacağını söylüyorlar. Bunlara
*rumaghder* (çamurcu) diyorlar. *Anlam çamurdur, yıkarsan bir şey
kalmaz*

Diğer bazıları ise *elmasçılar* (samlidder) diye anılıyor. Bunlar
çamurdan yıkanan sözün içinden elmasın *çıkabileceğini* iddia
ediyorlar. Bunlara ek çamurdan çıksa çıksa taş çıkacağını söyleyen
*taşçılar*, çamurun yıkanmak için değil yoğrulup heykel yapılması
gerektiğini söyleyen *heykelciler* ve buna benzer çeşitli okullar
var. Zerkubia felsefe ikliminin ekolleri daha çok hafriyat işiyle
ilgileniyor gibi.

Menkuşe üzerindeki tek anlaşmazlık bu konuda değil. Daha pek çok konuda
onun *aslında* ne demek istediğini tartışıyorlar. Bunlardan yeri
geldikçe bahsedeceğim.


------

*Pratik* isimli kitabı ise, Menkuşe'un günlük hayata ilişkin anlattığı
bazı tavsiyeleri içeriyor. *İnsan nasıl yaşamalıdır?* sorusundan
başlamış ve bunun için nasıl çalışması gerektiğini, nasıl konuşması,
düşünmesi, yemesi içmesi gerektiğini anlattığı yazılar
yazmış. Yazıların geneli 200-300 kelimeyi geçmiyor. İnsanların bu
kitabın *Teoriden* daha önemli olduğunu söylediklerini duydum. Onlara
göre Menkuşe, bu kitaba bazı şifreler eklemiş ve gelecekle ilgili
kehanetlerde bulunmuş. İnsanların her yerde bir kutsal kitaba ihtiyaç
duyduğunu gösteriyor bana kalırsa.

*Pratik'te* günlük hayata ilişkin tavsiyelerden ayrı bir de basit bir
toplum modeli anlatılıyor. Aslında verdiği tavsiyeleri de bu toplum
modeline ulaşmak için veriyor. Bireylerin nasıl olması gerektiğini
anlatırken, bir yandan da bu bireylerin inşa edeceği, etmesi beklenen
toplumu aktarıyor.

Bu toplum modeli Zerkubia'nın yapısına sirayet etmiş.  Bununla beraber
bu tarihten tanışık olduğumuz bir zorlama ve totaliter bir yönetim
anlamına gelmiyor.  Bana da ilk söylediklerinde, insanların hep aynı
şekilde düşündüğü ve giyindiği bir yer hayal etmiştim ancak gittiğimde
durumun bunun aksi olduğunu gördüm.

-----

Kitabı karıştırırken, aklımda kalan: Toplumla ilgili gözlemlerinden
biri, Liberal ülkelerde bireye *özgürlük* verirken, aynı zamanda
önemli görevler de yüklediği ancak bu görevlerin özgürlükleri anlamsız
kılacak derecede ağır olduğu. Menkuşe, özgürlüklerin sadece bir reklam
vasıtası olduğunu, Liberal Kapitalist düzenin insanları bu reklamlar
vasıtasıyla, kıramayacakları zincirlerle bağladığını söylüyor.

Bu kıramayacakları zincirlerin başında *iş* geliyor. İnsanların
çalışma özgürlüğü var gibi görünse de, gerçekte çalışma imkanları
kısıtlı çünkü ancak hayati riskler alarak çalışmayı reddedebilirler ve
hemen her ülkede işsizlik mevcut. Diğer zincir *sosyal bağlar* diyor
Menkuşe, bu bağların reddedilmesi imkansız ve insanları oldukları yere
bağlayan en önemli sebeplerden biri.

Bir Felsefe öğretmeninin Batı dünyasında sanat ve kültürün, Liberal
Kapitalist dünyadan bunalmış ve bulanmış insana sunulan bir deva
olarak anlatıldığını bildiğini kabul edebiliriz. Ancak ferdin hiçbir
zaman bir kültür taşıyıcısı olamayacağını, bunun için *çok küçük*
olduğunu, en etkin olduğu sosyal müessese olan ailesinde bile
kültürünün çocuklarına aktaracak gücü bulunmadığını söylüyor. Liberal
Kapitalist dünya, kültürü de bir ürün haline getirip, insanlara yeni
bağlar üretmekte becerikli diyor.

Bu gözlemi yaptıktan sonra, tanıdığımız totaliter kafalı düşünürlerin
aksine, devletin veya toplumun bir kültürü diğerlerine nazaran üstün
tutmasının adaletsizlik olduğunu da ekliyor. Yani kültürü korumanın
yolunun, tabiri caizse, *devlete yamanmak* olmadığını
anlatıyor. Liberalizmin kültürlere eşit yaklaşan tarafını
benimsediğini, mamafih bu kültürlerin hepsini aynı torbaya koyup
karıştırarak çıkardığı bulamacın kimseyi tatmin etmeyen ve kimsenin
*ontolojik* sorunlarına deva olmayan bir çorba olduğunu anlatıyor.

Bunun yerine diyor, devlet erklerinin bir kısmını paylaştığı ve
bireyler üzerinde etkin, kendi kanunlarını yapabilen *toplumcuklar*
oluşturmalı. Kültür tek başına yaşanabilen bir şey olmadığına göre, bu
toplumcuklar kültürlerin sahibi olmalı.


